---
# This role will install MySQL and create db user and give permissions.

 - name: Install mysql package
   apt: name={{ item }} state=present
   with_items:
     - mysql-server
     - MySQL-python

 - name: Start MySQL Service 
   service: name=mysql state=started enabled=yes

 - name: Create a Database
