---
 - name: Install PHP
   apt: name={{ item }} state=present
   with_items:
     - php5
     - php5-mysql
     - libapache2-mod-php5
     - php5-mcrypt
     - php5-gd
     - libssh2-php

 - name: create the info.php file
   template: src=info.php.j2 dest=/var/www/html/info.php
